# Sapien formula. Regenerated by goreleaser on each release of
# github.com/gs-sinha/sapien once the tap upload is enabled there; until
# then it is updated by hand from the release's checksums.txt.
class Sapien < Formula
  desc "Local-first, agent-native API workspace engine"
  homepage "https://github.com/gs-sinha/sapien"
  # Keep the explicit version: without it Homebrew scans "64" out of the
  # arm64 archive name on Linux (Cellar/sapien/64). brew audit calls it
  # redundant; it is not.
  version "1.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gs-sinha/sapien/releases/download/v1.2.0/sapien_1.2.0_darwin_arm64.tar.gz"
      sha256 "a0a198438311d8cc9e032025122d1527be6dfb4ca92d8036321885721f98c92d"
    else
      url "https://github.com/gs-sinha/sapien/releases/download/v1.2.0/sapien_1.2.0_darwin_amd64.tar.gz"
      sha256 "790dbf5307c0e7b0871f682f231df94f5ec6d98c8f8b181ddd301089d7b15256"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/gs-sinha/sapien/releases/download/v1.2.0/sapien_1.2.0_linux_arm64.tar.gz"
      sha256 "9f70284b74b524f902407c3cc9d038dc80a2f1c7473fc1e90cbd12bced19e038"
    else
      url "https://github.com/gs-sinha/sapien/releases/download/v1.2.0/sapien_1.2.0_linux_amd64.tar.gz"
      sha256 "7de3134966d86ed293fa780d9a73896f6d90bc37fe97ad8a92f8b3067d6c6910"
    end
  end

  def install
    bin.install "sapien"
  end

  test do
    system "#{bin}/sapien", "version"
  end
end
