# Sapien formula. Regenerated by goreleaser on each release of
# github.com/gs-sinha/sapien once the tap upload is enabled there; until
# then it is updated by hand from the release's checksums.txt.
class Sapien < Formula
  desc "Local-first, agent-native API workspace engine"
  homepage "https://github.com/gs-sinha/sapien"
  # Keep the explicit version: without it Homebrew scans "64" out of the
  # arm64 archive name on Linux (Cellar/sapien/64). brew audit calls it
  # redundant; it is not.
  version "1.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gs-sinha/sapien/releases/download/v1.0.1/sapien_1.0.1_darwin_arm64.tar.gz"
      sha256 "82fe794e67d5984ef7e8c09be2afcee0f8bd4494764b7cc588b7f471288caec7"
    else
      url "https://github.com/gs-sinha/sapien/releases/download/v1.0.1/sapien_1.0.1_darwin_amd64.tar.gz"
      sha256 "482b162691771785b946cc31f84345ac5e5b7dd2aaa365a130b78942f255f634"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/gs-sinha/sapien/releases/download/v1.0.1/sapien_1.0.1_linux_arm64.tar.gz"
      sha256 "e8d4f5e668bdf81e7ae02f8620de06e831c617dca48b5faa335c81c923c8d46b"
    else
      url "https://github.com/gs-sinha/sapien/releases/download/v1.0.1/sapien_1.0.1_linux_amd64.tar.gz"
      sha256 "535716384e6088cd1fa962fbdeb43d22d229b8510a1e0f520d8f1d8e5bb4a098"
    end
  end

  def install
    bin.install "sapien"
  end

  test do
    system "#{bin}/sapien", "version"
  end
end
